---

- name: 创建 containerd 配置文件目录
  file: path="{{ containerd_config_dir }}" state=directory

- name: 加载内核模块 overlay
  modprobe: name=overlay state=present

- name: 创建 crictl 配置
  template: src=containerd/crictl.yaml.j2 dest=/etc/crictl.yaml mode=644

- name: 配置 containerd 配置文件
  when: insecure_registries is defined and insecure_registries | length > 0
  template: src=containerd/config.toml.j2 dest={{ containerd_config_dir }}/config.toml mode=644
  tags: 'upgrade'

- name: 配置 containerd service 文件
  template:
    src: "containerd/{{ item }}.j2"
    dest: "{{ systemd_service_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - containerd.service
    - containerd.socket
  register: change_system_service
  tags: 'upgrade'

- name: 启动containerd，并设置开机启动
  when: change_system_service is succeeded
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: containerd_started
  tags: 'upgrade'

