
- block:
  - name: 准备 rbac 配置文件
    template: src="helm-rbac.yaml.j2" dest="{{ manifest_dir }}/helm-rbac.yaml"
    # template: src=strict-helm-rbac.yaml.j2 dest={{ manifest_dir }}/strict-helm-rbac.yaml

  - name: 创建 rbac 资源
    shell: "{{ bin_dir }}/kubectl apply -f {{ manifest_dir }}/helm-rbac.yaml"

  - name: 安装tiller
    shell: "{{ bin_dir }}/helm init --upgrade \
          --tiller-tls \
          --tiller-tls-verify \
          --tiller-tls-cert {{ pki_dir }}/{{ tiller_cert_cn }}.pem \
          --tiller-tls-key {{ pki_dir }}/{{ tiller_cert_cn }}-key.pem \
          --tls-ca-cert {{ pki_dir }}/ca.pem \
          --service-account {{ tiller_sa }} \
          --tiller-namespace {{ helm_namespace }} \
          --tiller-image {{ k8s_image_repo }}/kubernetes-helm/tiller:v{{ helm_version }} \
          --stable-repo-url {{ repo_url }}"

  - name: 轮询等待 tiller 运行，视下载镜像速度而定
    shell: "{{ bin_dir }}/kubectl get pod -n kube-system -o wide | grep tiller"
    register: tiller_status
    until: '"Running" in tiller_status.stdout and "0/1" not in tiller_status.stdout'
    retries: 10
    delay: "{{ retry_stagger | random + 30 }}"

  - name: 配置 helm 客户端
    shell: "cp -f {{ pki_dir }}/ca.pem {{ ansible_env.HOME }}/.helm/ca.pem && \
            cp -f {{ pki_dir }}/{{ helm_cert_cn }}.pem {{ ansible_env.HOME }}/.helm/cert.pem && \
            cp -f {{ pki_dir }}/{{ helm_cert_cn }}-key.pem {{ ansible_env.HOME }}/.helm/key.pem"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: 创建客户端配置文件存放目录
  file: path="{{ ansible_env.HOME }}/.helm" state=directory

- name: 从 deploy 节点分发 helm 和 tiller 配置文件
  synchronize: src="{{ ansible_env.HOME }}/.helm/" dest="{{ ansible_env.HOME }}/.helm/"

- name: 添加 helm 命令自动补全
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    regexp: 'helm completion'
    line: 'source <(helm completion bash)'

- name:  配置 helm tls 环境变量
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    regexp: "HELM_TLS_ENABLE"
    line: "export HELM_TLS_ENABLE=true"

- name: 当前会话加载 helm 命令自动补全
  shell: >
    {{ bin_dir }}/helm completion bash > /etc/bash_completion.d/helm;
    source /etc/bash_completion.d/helm
