# to set up 'kube-cluster' nodes
- hosts: masters
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-kubeconfig, node_role: 'master' }

- hosts: nodes
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-kubeconfig, node_role: 'node' }
