# kube-dns
- hosts: "{{ groups['masters'][0] }}"
  become: true
  gather_facts: false
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-addon, addon: "{{ addons.kubedns }}" }
