
- name: 安装 haproxy
  package: name=haproxy state=present

- name: 创建 haproxy 配置目录
  file: name={{ haproxy_config_dir }} state=directory

- name: 配置 haproxy systemd service 文件
  template:
    src: "haproxy.service.j2"
    dest: "{{ systemd_service_dir }}/haproxy.service"
    owner: root
    group: root
    mode: 0644

- name: 配置 haproxy
  template: src=haproxy.cfg.j2 dest={{ haproxy_config }}
