- name: 准备 alicloud-nas 配置目录
  file: name="{{ manifest_dir }}/storage/alicloud-nas" state=directory

- name: 生成 alicloud-nas 动态存储配置
  template:
    src: alicloud-nas/{{ item }}.j2
    dest: "{{ manifest_dir }}/storage/alicloud-nas/{{ item }}"
  with_items:
    - alicloud-disk.yaml
    - aliyun-nas-controller.yaml

#- name: 部署alicloud-disk存储
#  shell: "{{ bin_dir }}/kubectl apply -f {{ manifest_dir }}/storage/alicloud-nas/alicloud-disk.yaml"

- name: 部署 {{ storage.aliyun_nas.controller_name }} 动态存储
  shell: "{{ bin_dir }}/kubectl apply -f {{ manifest_dir }}/storage/alicloud-nas/aliyun-nas-controller.yaml"
