---

- name: 判断节点 {{ pkg.file }} 包文件是否存在
  stat: path="{{ cache_dir + pkg.file }}"
  register: check_files

- name: 从 deploy 节点同步 {{ pkg.file }} 文件包
  when: not check_files.stat.exists
  copy: src="{{ cache_dir + pkg.file }}" dest="{{ cache_dir + pkg.file }}"
  register: copy_files
  ignore_errors: true

- name: "下载 {{ pkg.file }} 文件包"
  when: copy_files is failed
  get_url:
    url: "{{ pkg.url }}/{{ pkg.file }}"
    dest: "{{ cache_dir + pkg.file }}"
    validate_certs: False
  environment:
    http_proxy: "{{ proxy_env.http_proxy }}"
    https_proxy: "{{ proxy_env.https_proxy }}"
  register: pkg_download

- name: "从 {{ pkg.file }} 中提取文件"
  when: copy_files is succeeded or "OK" in pkg_download.msg
  unarchive:
    src: "{{ cache_dir + pkg.file }}"
    dest: "{{ pkg.dir }}"
    copy: no
    extra_opts: "{{ pkg.unarchive.extra_opt }}"
