{
 "title": "Kubernetes / GPU Resources / Pod",
 "tags": [
  "kubernetes-mixin",
  "GPU"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "Node_Name",
    "query": "label_values(node_uname_info{instance=~\"$Instance:9100\"}, nodename)"
   },
   {
    "name": "Namespace",
    "query": "label_values(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}, namespace)"
   },
   {
    "name": "GPU_Pod",
    "query": "label_values(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", namespace=~\"$Namespace\", node=~\"$Node_Name\"}, pod)"
   },
   {
    "name": "Container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=\"$GPU_Pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_duty_cycle{pod_name=\"$GPU_Pod\"}",
     "legendFormat": "{{model}}, {{acc_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage(byte)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_memory_used_bytes{pod_name=\"$GPU_Pod\"}",
     "legendFormat": "{{model}}, {{acc_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$Namespace\", pod_name=\"$GPU_Pod\", container_name=~\"$Container\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\", namespace=\"$Namespace\", pod=\"$GPU_Pod\", container=~\"$Container\"})",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\", namespace=\"$Namespace\", pod=\"$GPU_Pod\", container=~\"$Container\"})",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container_name!=\"POD\",pod_name=\"$GPU_Pod\"}[1m]))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{job=\"kubelet\", pod_name=\"$GPU_Pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}