{
 "title": "Kubernetes / GPU Resources / Node",
 "tags": [
  "kubernetes-mixin",
  "GPU"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "Node_Name",
    "query": "label_values(node_uname_info{instance=~\"$Instance:9100\"}, nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Used GPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", node=\"$Node_Name\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total GPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nvidia_gpu_num_devices{instance=\"$Instance:9445\"}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Usage（byte）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage（mW）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  }
 ]
}