- name: 创建 docker 用户组
  group:
    name: docker
    state: present

- name: 创建 docker 用户
  user:
    name: docker
    comment: "Docker user"
    shell: /sbin/nologin
    state: present
    system: yes
    groups: docker

- name: 检查 container runtime sysctl 文件是否存在
  stat: path=/etc/sysctl.d/99-docker.conf
  register: check_sysctl_conf

- name: 将 bridge-netfilter 和 ip-forward 写入系统变量
  when: not check_sysctl_conf.stat.exists
  copy:
    content: |
      net.ipv4.ip_forward=1
      net.bridge.bridge-nf-call-ip6tables=1
      net.bridge.bridge-nf-call-iptables=1
      net.ipv4.conf.all.arp_ignore=1
      net.ipv4.conf.all.arp_announce=2
    dest: /etc/sysctl.d/99-docker.conf

- name: sysctl 加载 bridge-netfilter 和 ip-forward 系统变量
  command: "sysctl -p /etc/sysctl.d/99-docker.conf"

- name: 配置 Docker engine service 文件
  template:
    src: "docker/{{ item }}.j2"
    dest: "{{ systemd_service_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - docker.service
    - docker.socket
  register: change_system_service
  tags: upgrade

- name: docker命令自动补全
  copy: src=docker dest=/etc/bash_completion.d/docker mode=0644

- name: 创建 docker 配置文件目录
  file: path="{{ docker_config_dir }}" state=directory

- name: 配置 daemon.json
  template: src=docker/daemon.json.j2 dest={{ docker_config_dir }}/daemon.json
  tags: upgrade

- name: flush-iptables
  shell: >
    iptables -P INPUT ACCEPT;
    iptables -F && iptables -X;
    iptables -F -t nat && iptables -X -t nat;
    iptables -F -t raw && iptables -X -t raw;
    iptables -F -t mangle && iptables -X -t mangle;
    iptables -P FORWARD ACCEPT

- name: 启动 Docker socket
  when: change_system_service is succeeded
  systemd:
    name: docker.socket
    daemon_reload: yes
    state: started
    enabled: yes
  register: docker_socket_started
  tags: 'upgrade'

- name: 启动 Docker engine，并设置开机启动
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker
  tags: 'upgrade'

- name: 安装 docker-tag
  copy: src=docker-tag dest={{ bin_dir }}/docker-tag mode=0755

- name: 当前会话加载 docker 命令自动补全
  shell: >
    source /etc/bash_completion.d/docker
