---

- name: 停止运行 flanneld
  systemd: name=flanneld state=stopped enabled=no
  ignore_errors: True

- name: 删除所有 flanneld 文件及目录
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ flanneld_env_dir }}"
    - "{{ flanneld_etc_dir }}"
    - "{{ package.flannel.dir }}"
    - "{{ bin_dir }}/flanneld"
    - "{{ cni_etc_dir }}/10-flannel.conflist"
    - "{{ systemd_service_dir }}/flanneld.service"
    - "{{ etc_systemd_service_dir }}/flanneld.service"
  ignore_errors: True
