---

- when: container_runtime == 'nvidia-docker'
  raw: "nvidia-smi"
  ignore_errors: True
  register: check_driver

- include_tasks: containerd/main.yml

# nvidia-docker runtime
- when:
  - container_runtime == 'nvidia-docker'
  - "'not found' not in check_driver.stdout"
  include_tasks: nvidia-docker/main.yml

# docker runtime
- when: container_runtime == 'docker' or container_runtime == 'nvidia-docker'
  include_tasks: docker/main.yml
