# WARNNING: clean 'etcd' nodes service & data
- hosts: etcds
  become: true
  roles:
   - { role: cluster-default }
   - { role: cluster-path }
  tasks:
  - name: 停止运行 etcd
    systemd: name=etcd state=stopped enabled=no
    ignore_errors: True

  - name: 删除所有 etcd 文件及目录
    file: path="{{ item }}" state=absent
    with_items:
      - "{{ etcd_config_dir }}"
      - "{{ etcd_data_dir }}"
      - "{{ bin_dir }}/etcd"
      - "{{ bin_dir }}/etcdctl"
      - "{{ systemd_service_dir }}/etcd.service"
    ignore_errors: True
